CC=/usr/src/arm-linux-3.3/toolchain_gnueabi-4.4.0_ARMv5TE/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc

CFLAGS = -I/usr/src/arm-linux-3.3/module/include/lcd200_v3

OBJ=edid_test

all:
	$(CC) $(CFLAGS) edid.c -o $(OBJ)
clean:
	rm edid_test


